### ISSUE TITLE
just a small question

### ISSUE THREAD

**Issue by dutchsing009** [polvanrijn/VoiceMe#2]
Really nice paper , i noticed voiceMe and wavthruvec got released on arxiv.org 2 days apart and voiceMe got the fast code implementation and wavthruvec didn't ???/ will it ever drop ?? the 2 papers are a true masterpiece !! sorry if i asked in the wrong place but didn't wanna annoy you by emailing you.

Thank you in advance : )

**Comment by polvanrijn** [comment]
I am glad you liked the papers! :-) We are not planning on publishing the code and pretrained model of WavThruVec in the near future.
