### ISSUE TITLE
No reaction for changing PCA / speaker embedding

### ISSUE THREAD

**Issue by NikitaKononov** [polvanrijn/VoiceMe#3]
Hello
You provide ljspeech trained model, but it has parameter 'n_speaker' = 0, so speaker embedding chanhing (by pca in flask playground or manually in code) doesn't take any effect

This is normal behaviour? 
It looks like all the infrastructure in project (for pca/spk_emd) is developed for VCTK model, but you don't provide it

I am an newbie in DS, so I might have misunderstood something. Thanks!

**Comment by polvanrijn** [comment]
Hello Nikita!

Sorry, this was my mistake. I provided the wrong checkpoint! You should download the [VCTK checkpoint](https://drive.google.com/file/d/11aHOlhnxzjpdWDpsz1vFDCzbeEfoIxru). I also updated the README.

Thanks for pointing this out!

Feel free to reopen, if something is not working.

Cheers,
Pol
