### ISSUE TITLE
is that possible deal with Chinese voice?

### ISSUE THREAD

**Issue by lucasjinreal** [polvanrijn/VoiceMe#5]
is that possible deal with Chinese voice?

**Comment by polvanrijn** [comment]
Yes, definitely. But you would need to get a trained multispeaker TTS system first. Do you have one in mind?

**Comment by lucasjinreal** [comment]
I am pretty new in tts. does fastspeech2 able to do multipspeaker tts?

**Comment by polvanrijn** [comment]
I think this should work for all TTS models that have speaker embeddings and were trained on multiple speakers. You would need to do some research on your own on which models fit your use case. I am closing the issue now. Feel free to reopen if you have some specific questions about this repository.
